name: Java CI with Maven

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Run PMD
        run: mvn pmd:check

      - name: Archive PMD report
        if: failure() && steps.pmd.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: target/pmd.xml